# netlify.toml
# Basic configuration for a Netlify deployment
[build]
  publish = "" # Directory to publish
  command = "node ./common/script/specLinks.mjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview]
  NODE_ENV = "Deploy"
  command = "node ./common/script/specLinks.mjs"

[context.branch-deploy]
  command = "node ./common/script/specLinks.mjs"
