# netlify.toml
# Basic configuration for a Netlify deployment
[build]
  publish = "public" # Directory to publish
  command = "./common/script/pr-preview.sh"

[[redirects]]
  from = "/*"
  to = "index.html"
  status = 200

[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "Deploy-review"
  command = "bash ./common/script/pr-preview.sh"

[context.branch-deploy.environment]
  command = "bash ./common/script/pr-preview.sh"
