name: Deploy
on:
  push:
    branches:
      - monorepo_history--accname
    paths:
      - index.html
      - /accname/**
      - /core-aam/**
      - /dpub-aam/**
      - /dpub-aria/**
      - /graphics-aam/**
      - /graphics-aria/**
      - /html-aam/**
      - /html-aria/**
      - /svg-aam/**
      - /mathml-aam/**
      - /mathml-aria/**

jobs:
  publish-editors-draft:
    runs-on: ubuntu-latest
    if: github.repository == 'daniel-montalvo/aria'
    strategy:
      fail-fast: false
      matrix:
        include:
            - repo: daniel-montalvo/accname
              branch: gh-pages
              sourcepath: /accname/
            - repo: daniel-montalvo/core-aam
              branch: gh-pages
              sourcepath: /core-aam/
            - repo: daniel-montalvo/dpub-aam
              branch: gh-pages
              sourcepath: /dpub-aam/
            - repo: daniel-montalvo/dpub-aria
              branch: gh-pages
              sourcepath: /dpub-aria/
            - repo: daniel-montalvo/graphics-aam
              branch: gh-pages
              sourcepath: /graphics-aam/
            - repo: daniel-montalvo/graphics-aria
              branch: gh-pages
              sourcepath: /graphics-aria/
            - repo: daniel-montalvo/math-aria
              branch: gh-pages
              sourcepath: /math-aria/
            - repo: daniel-montalvo/mathml-aam
              branch: gh-pages
              sourcepath: /mathml-aam/
            - repo: daniel-montalvo/svg-aam
              branch: gh-pages
              sourcepath: /svg-aam/
            - repo: daniel-montalvo/html-aam
              branch: aria-common-sync
              sourcepath: /html-aam/
        
    steps:
    - uses: actions/checkout@v3

    - uses: actions/checkout@v3
      with:
        repository: ${{ matrix.repo }}
        path: ${{ matrix.repo }}
        ref: ${{ matrix.branch }}
        token: ${{ secrets.ARIA_COMMON }}

    - name: Cleanup old files
      run: |
        rm -rf ${{ matrix.repo }}/common/
        rm ${{ matrix.repo }}/index.html

    - name: Build respec
      run: |
        npx respec --src ./${{ matrix.repo.sourcepath }}/index.html --out ${{ matrix.repo }}/index.html
    - name: Copy files
      run: |
        mkdir ${{ matrix.repo }}/common
        cp -R README.md ${{ matrix.repo }}/common
        cp -R acknowledgements.html ${{ matrix.repo }}/common
        cp -R biblio.js ${{ matrix.repo }}/common
        cp -R terms.html ${{ matrix.repo }}/common
        cp -R acknowledgements ${{ matrix.repo }}/common
        cp -R css ${{ matrix.repo }}/common
        cp -R img ${{ matrix.repo }}/common
        cp -R script ${{ matrix.repo }}/common
        cp -R utility ${{ matrix.repo }}/common

    - name: Commit back
      run: |
        cd ${{ matrix.repo }}
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add --all
        git commit -m "chore: sync from w3c/aria-common" -m "Generated by https://github.com/w3c/aria-common/commit/${{ github.sha }}" || true
        git push
