name: Deploy
on:
  pull_request:
  push:
    branches:
     - monorepo_history--accname
    paths:
     - index.html
     - /accname/**
     - /core-aam/**
     - /dpub-aam/**
     - /dpub-aria/**
     - /graphics-aam/**
     - /graphics-aria/**
     - /html-aam/**
     - /html-aria/**
     - /svg-aam/**
     - /mathml-aam/**
     - /mathml-aria/**

jobs:
  publish-editors-draft:
    runs-on: ubuntu-latest
    if: github.repository == 'w3c/aria'
    strategy:
      fail-fast: false
      matrix:
        include:
            - repo: w3c/accname
              branch: gh-pages
              sourcepath: /accname/
            - repo: w3c/core-aam
              branch: gh-pages
              sourcepath: /core-aam/
            - repo: w3c/dpub-aam
              branch: gh-pages
              sourcepath: /dpub-aam/
            - repo: w3c/dpub-aria
              branch: gh-pages
              sourcepath: /dpub-aria/
            - repo: w3c/graphics-aam
              branch: gh-pages
              sourcepath: /graphics-aam/
            - repo: w3c/graphics-aria
              branch: gh-pages
              sourcepath: /graphics-aria/
            - repo: w3c/math-aria
              branch: gh-pages
              sourcepath: /math-aria/
            - repo: w3c/mathml-aam
              branch: gh-pages
              sourcepath: /mathml-aam/
            - repo: w3c/svg-aam
              branch: gh-pages
              sourcepath: /svg-aam/
            - repo: w3c/html-aam
              branch: aria-common-sync
              sourcepath: /html-aam/
        
    steps:
    - uses: actions/checkout@v4

    - uses: actions/checkout@v4
      with:
        repository: ${{ matrix.repo }}
        ref: ${{ matrix.branch }}
        token: ${{ secrets.GITHUB_TOKEN }}

        
    - name: Cleanup old files
      run: |
        rm -rf ${{ matrix.repo }}/common/
        rm ${{ matrix.repo }}/index.html

    - name: Build respec
      run: |
        npm install respec@latest  
        npx respec --src ${{ matrix.repo.sourcepath }}/index.html --out ${{ matrix.repo }}/index.html
    - name: Copy files
      run: |
        mkdir ${{ matrix.repo }}/common
        cd /common/
        cp -R README.md ${{ matrix.repo }}/common
        cp -R acknowledgements.html ${{ matrix.repo }}/common
        cp -R biblio.js ${{ matrix.repo }}/common
        cp -R terms.html ${{ matrix.repo }}/common
        cp -R acknowledgements ${{ matrix.repo }}/common
        cp -R css ${{ matrix.repo }}/common
        cp -R img ${{ matrix.repo }}/common
        cp -R script ${{ matrix.repo }}/common
        cp -R utility ${{ matrix.repo }}/common

    - name: Commit back
      run: |
        cd ${{ matrix.repo }}
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add --all
        git commit -m "editors draft"
        git push
