name: Build and Deploy Editor's Drafts
on:
  pull_request:
  push:
    branches: [monorepo_history--accname]
    paths:
     - index.html
     - /accname/**
     - /core-aam/**
     - /dpub-aam/**
     - /dpub-aria/**
     - /graphics-aam/**
     - /graphics-aria/**
     - /html-aam/**
     - /html-aria/**
     - /svg-aam/**
     - /mathml-aam/**
     - /mathml-aria/**

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        spec: 
          - name: 'accname'
            branch: 'gh-pages'
          # Others to come

    steps:
      - name: Checkout monorepo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Install ReSpec
        run: npm install -g respec@latest

      - name: Build Respec
        run: |
          cd ${{ matrix.spec.name }}
          npx respec --src index.html --out .Overview.html
          cd ..

      - name : Checkout deployment repositories
        uses: actions/checkout@v4
        with:
          repository: w3c/${{ matrix.spec.name }}
          ref: ${{ matrix.spec.branch }}
          path: w3c/${{ matrix.spec.name }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name    : Copy files
        run: |
          cp ./${{ matrix.spec.name }}Overview.html Overview.html

      - name: Push changes
        run: |
          cd ./deploy
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update generated files"
          git push