name: Update PR Links

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  update-pr-links:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'

      - name: Install dependencies
        run: npm install axios yargs

      - name: Generate preview links and update PR
        run: |
          node common/script/prLinks.mjs \
            --repo ${{ github.repository }} \
            --pull_request_number ${{ github.event.pull_request.number }} \
            --token ${{ secrets.GITHUB_TOKEN }} \
            --update_pr